package com.yazuo.weixin.vo;

import java.util.Date;

/**
* @ClassName WxcoffeeCzFlag
* @Description  咖啡陪你充值状态
* @author sundongfeng@yazuo.com
* @date 2014-7-8 下午3:19:37
* @version 1.0
*/
public class WxcoffeeCzFlag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_coffee_czflag.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_coffee_czflag.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_coffee_czflag.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_coffee_czflag.card_no
     *
     * @mbggenerated
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_coffee_czflag.brand_id
     *
     * @mbggenerated
     */
    private String brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_coffee_czflag.amount
     *
     * @mbggenerated
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_coffee_czflag.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_coffee_czflag.remark
     *
     * @mbggenerated
     */
    private String remark;
    
    //2014-7-8 add by sundongfeng
    private Date createTime;
    
    public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_coffee_czflag.id
     *
     * @return the value of weixin_coffee_czflag.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_coffee_czflag.id
     *
     * @param id the value for weixin_coffee_czflag.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_coffee_czflag.out_trade_no
     *
     * @return the value of weixin_coffee_czflag.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_coffee_czflag.out_trade_no
     *
     * @param outTradeNo the value for weixin_coffee_czflag.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_coffee_czflag.mobile
     *
     * @return the value of weixin_coffee_czflag.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_coffee_czflag.mobile
     *
     * @param mobile the value for weixin_coffee_czflag.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_coffee_czflag.card_no
     *
     * @return the value of weixin_coffee_czflag.card_no
     *
     * @mbggenerated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_coffee_czflag.card_no
     *
     * @param cardNo the value for weixin_coffee_czflag.card_no
     *
     * @mbggenerated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_coffee_czflag.brand_id
     *
     * @return the value of weixin_coffee_czflag.brand_id
     *
     * @mbggenerated
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_coffee_czflag.brand_id
     *
     * @param brandId the value for weixin_coffee_czflag.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId == null ? null : brandId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_coffee_czflag.amount
     *
     * @return the value of weixin_coffee_czflag.amount
     *
     * @mbggenerated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_coffee_czflag.amount
     *
     * @param amount the value for weixin_coffee_czflag.amount
     *
     * @mbggenerated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_coffee_czflag.status
     *
     * @return the value of weixin_coffee_czflag.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_coffee_czflag.status
     *
     * @param status the value for weixin_coffee_czflag.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_coffee_czflag.remark
     *
     * @return the value of weixin_coffee_czflag.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_coffee_czflag.remark
     *
     * @param remark the value for weixin_coffee_czflag.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	public String toString() {
		return "WxcoffeeCzFlag [id=" + id + ", outTradeNo=" + outTradeNo
				+ ", mobile=" + mobile + ", cardNo=" + cardNo + ", brandId="
				+ brandId + ", amount=" + amount + ", status=" + status
				+ ", remark=" + remark + ", createTime=" + createTime + "]";
	}
    
}