package com.yazuo.weixin.vo;

/**
* @ClassName WxPayCard
* @Description 支付后，绑定券
* @author sundongfeng@yazuo.com
* @date 2014-6-17 上午9:03:22
* @version 1.0
*/
public class WxPayCard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_card_bind.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_card_bind.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_card_bind.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_card_bind.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_card_bind.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_card_bind.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_card_bind.partner_id
     *
     * @mbggenerated
     */
    private String partnerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_card_bind.brand_id
     *
     * @mbggenerated
     */
    private String brandId;

    
    private String res_card_no;//李斌接口返回列表中的id
    
    
    public String getRes_card_no() {
		return res_card_no;
	}

	public void setRes_card_no(String res_card_no) {
		this.res_card_no = res_card_no;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_card_bind.id
     *
     * @return the value of weixin_pay_card_bind.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_card_bind.id
     *
     * @param id the value for weixin_pay_card_bind.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_card_bind.mobile
     *
     * @return the value of weixin_pay_card_bind.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_card_bind.mobile
     *
     * @param mobile the value for weixin_pay_card_bind.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_card_bind.open_id
     *
     * @return the value of weixin_pay_card_bind.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_card_bind.open_id
     *
     * @param openId the value for weixin_pay_card_bind.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_card_bind.card_id
     *
     * @return the value of weixin_pay_card_bind.card_id
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_card_bind.card_id
     *
     * @param cardId the value for weixin_pay_card_bind.card_id
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_card_bind.out_trade_no
     *
     * @return the value of weixin_pay_card_bind.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_card_bind.out_trade_no
     *
     * @param outTradeNo the value for weixin_pay_card_bind.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_card_bind.create_time
     *
     * @return the value of weixin_pay_card_bind.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_card_bind.create_time
     *
     * @param createTime the value for weixin_pay_card_bind.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_card_bind.partner_id
     *
     * @return the value of weixin_pay_card_bind.partner_id
     *
     * @mbggenerated
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_card_bind.partner_id
     *
     * @param partnerId the value for weixin_pay_card_bind.partner_id
     *
     * @mbggenerated
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId == null ? null : partnerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_card_bind.brand_id
     *
     * @return the value of weixin_pay_card_bind.brand_id
     *
     * @mbggenerated
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_card_bind.brand_id
     *
     * @param brandId the value for weixin_pay_card_bind.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId == null ? null : brandId.trim();
    }
}