package com.yazuo.weixin.vo;


/**
* @ClassName WxOrder
* @Description 支付流水
* @author sundongfeng@yazuo.com
* @date 2014-6-17 上午9:03:03
* @version 1.0
*/
public class WxOrder {
	private String cardId;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.notify_id
     *
     * @mbggenerated
     */
    private String notify_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.partner
     *
     * @mbggenerated
     */
    private String partner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.bank_billno
     *
     * @mbggenerated
     */
    private String bank_billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.transaction_id
     *
     * @mbggenerated
     */
    private String transaction_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.product_fee
     *
     * @mbggenerated
     */
    private Long product_fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.transport_fee
     *
     * @mbggenerated
     */
    private Long transport_fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.discount
     *
     * @mbggenerated
     */
    private Long discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.total_fee
     *
     * @mbggenerated
     */
    private Long total_fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.time_begin
     *
     * @mbggenerated
     */
    private String timeBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.time_end
     *
     * @mbggenerated
     */
    private String time_end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.trade_state
     *
     * @mbggenerated
     */
    private String trade_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.out_trade_no
     *
     * @mbggenerated
     */
    private String out_trade_no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.nonce_tr
     *
     * @mbggenerated
     */
    private String nonceTr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.fee_type
     *
     * @mbggenerated
     */
    private String fee_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.trade_mode
     *
     * @mbggenerated
     */
    private String trade_mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.sign_type
     *
     * @mbggenerated
     */
    private String sign_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.buyer_alias
     *
     * @mbggenerated
     */
    private String buyerAlias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.input_charset
     *
     * @mbggenerated
     */
    private String input_charset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.bank_type
     *
     * @mbggenerated
     */
    private String bank_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.product_info
     *
     * @mbggenerated
     */
    private String productInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.pay_info
     *
     * @mbggenerated
     */
    private String payInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.is_subscribe
     *
     * @mbggenerated
     */
    private String isSubscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_order.app_signature
     *
     * @mbggenerated
     */
    private String appSignature;

    private Long count;
    
    private String deliverState;
    
    private String brandId; //商户brandid
    
	public String getBrandId() {
		return brandId;
	}

	public void setBrandId(String brandId) {
		this.brandId = brandId;
	}

	public String getDeliverState() {
		return deliverState;
	}

	public void setDeliverState(String deliverState) {
		this.deliverState = deliverState;
	}

	public Long getCount() {
		return count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

	public String getCardId() {
		return cardId;
	}

	public void setCardId(String cardId) {
		this.cardId = cardId;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getOpenId() {
		return openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	public String getAppId() {
		return appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	public String getNotify_id() {
		return notify_id;
	}

	public void setNotify_id(String notify_id) {
		this.notify_id = notify_id;
	}

	public String getPartner() {
		return partner;
	}

	public void setPartner(String partner) {
		this.partner = partner;
	}

	public String getBank_billno() {
		return bank_billno;
	}

	public void setBank_billno(String bank_billno) {
		this.bank_billno = bank_billno;
	}

	public String getTransaction_id() {
		return transaction_id;
	}

	public void setTransaction_id(String transaction_id) {
		this.transaction_id = transaction_id;
	}

	public String getSign() {
		return sign;
	}

	public void setSign(String sign) {
		this.sign = sign;
	}

	public Long getProduct_fee() {
		return product_fee;
	}

	public void setProduct_fee(Long product_fee) {
		this.product_fee = product_fee;
	}

	public Long getTransport_fee() {
		return transport_fee;
	}

	public void setTransport_fee(Long transport_fee) {
		this.transport_fee = transport_fee;
	}

	public Long getDiscount() {
		return discount;
	}

	public void setDiscount(Long discount) {
		this.discount = discount;
	}

	public Long getTotal_fee() {
		return total_fee;
	}

	public void setTotal_fee(Long total_fee) {
		this.total_fee = total_fee;
	}

	public String getTimeBegin() {
		return timeBegin;
	}

	public void setTimeBegin(String timeBegin) {
		this.timeBegin = timeBegin;
	}

	public String getTime_end() {
		return time_end;
	}

	public void setTime_end(String time_end) {
		this.time_end = time_end;
	}

	public String getTrade_state() {
		return trade_state;
	}

	public void setTrade_state(String trade_state) {
		this.trade_state = trade_state;
	}

	public String getOut_trade_no() {
		return out_trade_no;
	}

	public void setOut_trade_no(String out_trade_no) {
		this.out_trade_no = out_trade_no;
	}

	public String getNonceTr() {
		return nonceTr;
	}

	public void setNonceTr(String nonceTr) {
		this.nonceTr = nonceTr;
	}

	public String getFee_type() {
		return fee_type;
	}

	public void setFee_type(String fee_type) {
		this.fee_type = fee_type;
	}

	public String getTrade_mode() {
		return trade_mode;
	}

	public void setTrade_mode(String trade_mode) {
		this.trade_mode = trade_mode;
	}

	public String getSign_type() {
		return sign_type;
	}

	public void setSign_type(String sign_type) {
		this.sign_type = sign_type;
	}

	public String getBuyerAlias() {
		return buyerAlias;
	}

	public void setBuyerAlias(String buyerAlias) {
		this.buyerAlias = buyerAlias;
	}

	public String getInput_charset() {
		return input_charset;
	}

	public void setInput_charset(String input_charset) {
		this.input_charset = input_charset;
	}

	public String getBank_type() {
		return bank_type;
	}

	public void setBank_type(String bank_type) {
		this.bank_type = bank_type;
	}

	public String getProductInfo() {
		return productInfo;
	}

	public void setProductInfo(String productInfo) {
		this.productInfo = productInfo;
	}

	public String getPayInfo() {
		return payInfo;
	}

	public void setPayInfo(String payInfo) {
		this.payInfo = payInfo;
	}

	public String getIsSubscribe() {
		return isSubscribe;
	}

	public void setIsSubscribe(String isSubscribe) {
		this.isSubscribe = isSubscribe;
	}

	public String getAppSignature() {
		return appSignature;
	}

	public void setAppSignature(String appSignature) {
		this.appSignature = appSignature;
	}

}