package com.yazuo.weixin.vo;

import java.util.Date;

/**
* @ClassName WxPayCouponState
* @Description 券状态表，记录券是否生成成功
* @author sundongfeng@yazuo.com
* @date 2014-6-17 上午9:04:24
* @version 1.0
*/
public class WxPayCouponState implements java.io.Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_coupon_state.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_coupon_state.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_coupon_state.total_fee
     *
     * @mbggenerated
     */
    private Long totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_coupon_state.counter
     *
     * @mbggenerated
     */
    private Long counter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_coupon_state.card_id
     *
     * @mbggenerated
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_coupon_state.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_coupon_state.trade_state
     *
     * @mbggenerated
     */
    private String tradeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_coupon_state.card_state
     *
     * @mbggenerated
     */
    private String cardState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_coupon_state.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_coupon_state.transaction_id
     *
     * @mbggenerated
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_coupon_state.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_pay_coupon_state.partner_id
     *
     * @mbggenerated
     */
    private String partnerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_coupon_state.id
     *
     * @return the value of weixin_pay_coupon_state.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_coupon_state.id
     *
     * @param id the value for weixin_pay_coupon_state.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_coupon_state.mobile
     *
     * @return the value of weixin_pay_coupon_state.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_coupon_state.mobile
     *
     * @param mobile the value for weixin_pay_coupon_state.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_coupon_state.total_fee
     *
     * @return the value of weixin_pay_coupon_state.total_fee
     *
     * @mbggenerated
     */
    public Long getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_coupon_state.total_fee
     *
     * @param totalFee the value for weixin_pay_coupon_state.total_fee
     *
     * @mbggenerated
     */
    public void setTotalFee(Long totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_coupon_state.counter
     *
     * @return the value of weixin_pay_coupon_state.counter
     *
     * @mbggenerated
     */
    public Long getCounter() {
        return counter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_coupon_state.counter
     *
     * @param counter the value for weixin_pay_coupon_state.counter
     *
     * @mbggenerated
     */
    public void setCounter(Long counter) {
        this.counter = counter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_coupon_state.card_id
     *
     * @return the value of weixin_pay_coupon_state.card_id
     *
     * @mbggenerated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_coupon_state.card_id
     *
     * @param cardId the value for weixin_pay_coupon_state.card_id
     *
     * @mbggenerated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_coupon_state.open_id
     *
     * @return the value of weixin_pay_coupon_state.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_coupon_state.open_id
     *
     * @param openId the value for weixin_pay_coupon_state.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_coupon_state.trade_state
     *
     * @return the value of weixin_pay_coupon_state.trade_state
     *
     * @mbggenerated
     */
    public String getTradeState() {
        return tradeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_coupon_state.trade_state
     *
     * @param tradeState the value for weixin_pay_coupon_state.trade_state
     *
     * @mbggenerated
     */
    public void setTradeState(String tradeState) {
        this.tradeState = tradeState == null ? null : tradeState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_coupon_state.card_state
     *
     * @return the value of weixin_pay_coupon_state.card_state
     *
     * @mbggenerated
     */
    public String getCardState() {
        return cardState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_coupon_state.card_state
     *
     * @param cardState the value for weixin_pay_coupon_state.card_state
     *
     * @mbggenerated
     */
    public void setCardState(String cardState) {
        this.cardState = cardState == null ? null : cardState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_coupon_state.create_time
     *
     * @return the value of weixin_pay_coupon_state.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_coupon_state.create_time
     *
     * @param createTime the value for weixin_pay_coupon_state.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_coupon_state.transaction_id
     *
     * @return the value of weixin_pay_coupon_state.transaction_id
     *
     * @mbggenerated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_coupon_state.transaction_id
     *
     * @param transactionId the value for weixin_pay_coupon_state.transaction_id
     *
     * @mbggenerated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_coupon_state.out_trade_no
     *
     * @return the value of weixin_pay_coupon_state.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_coupon_state.out_trade_no
     *
     * @param outTradeNo the value for weixin_pay_coupon_state.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_pay_coupon_state.partner_id
     *
     * @return the value of weixin_pay_coupon_state.partner_id
     *
     * @mbggenerated
     */
    public String getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_pay_coupon_state.partner_id
     *
     * @param partnerId the value for weixin_pay_coupon_state.partner_id
     *
     * @mbggenerated
     */
    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId == null ? null : partnerId.trim();
    }
}