/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-03-30 09:53:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <title>登录</title>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"portal/origin/asset/base.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"portal/origin/asset/login.css\">\r\n");
      out.write("        <script src=\"portal/origin/asset/third/jquery-1.11.1.js\"></script>\r\n");
      out.write("        <script src=\"portal/origin/asset/third/json2.js\"></script>\r\n");
      out.write("        <script src=\"portal/origin/asset/third/store.js\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("            jQuery(function ($) {\r\n");
      out.write("                var winEl = $(window),\r\n");
      out.write("                    bodyEl = $('body'),\r\n");
      out.write("                    loginFormEl = $('.login-form', bodyEl),\r\n");
      out.write("                    accountEl = $('.account', loginFormEl),\r\n");
      out.write("                    pwdEl = $('.pwd', loginFormEl),\r\n");
      out.write("                    rememberCkEl = $('#is-remember'),\r\n");
      out.write("                    accountStore = store.get('account'),\r\n");
      out.write("                    forgetPwdLinkEl = $('.forget-pwd-link', bodyEl),\r\n");
      out.write("                    forgetPwdDialogEl = $('.find-pwd-dialog', bodyEl),\r\n");
      out.write("                    forgetPwdOlEl = $('.find-pwd-overlay', bodyEl),\r\n");
      out.write("                    noFlashTipEl = $('.no-flash-tip', loginFormEl),\r\n");
      out.write("                    submitEl = $('.f-submit', loginFormEl);\r\n");
      out.write("                //尝试关闭录音播放\r\n");
      out.write("                var softPos = document.getElementById('softPos');\r\n");
      out.write("                if (softPos && softPos.RecordClose) {\r\n");
      out.write("                    softPos.RecordClose();\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                //判断是否支持记住密码\r\n");
      out.write("                if (!store.enabled) {\r\n");
      out.write("                    alert('当前浏览器不支持本地存储，请联系系统管理员');\r\n");
      out.write("                    rememberCkEl.prop('disabled', true);\r\n");
      out.write("                } else {\r\n");
      out.write("                    rememberCkEl.prop('checked', true);\r\n");
      out.write("                    //默认填写最后一次登录的账号信息\r\n");
      out.write("                    if (accountStore) {\r\n");
      out.write("                        accountEl.val(accountStore[accountStore.length - 1].account);\r\n");
      out.write("                        pwdEl.val(accountStore[accountStore.length - 1].pwd);\r\n");
      out.write("                    }\r\n");
      out.write("                    //监听account的change事件，自动填充对应的密码\r\n");
      out.write("                    accountEl.change(function () {\r\n");
      out.write("                        var account = $.trim($(this).val()),\r\n");
      out.write("                            i;\r\n");
      out.write("                        if (accountStore) {\r\n");
      out.write("                            for (i = 0; i < accountStore.length; i++) {\r\n");
      out.write("                                if (accountStore[i].account == account && rememberCkEl.prop('checked')) {\r\n");
      out.write("                                    pwdEl.val(accountStore[i].pwd);\r\n");
      out.write("                                    break;\r\n");
      out.write("                                }\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("                //忘记密码\r\n");
      out.write("                forgetPwdLinkEl.click(function () {\r\n");
      out.write("                    forgetPwdDialogEl.css({\r\n");
      out.write("                        \"top\": (winEl.height() - forgetPwdDialogEl.outerHeight()) / 2,\r\n");
      out.write("                        \"left\": (winEl.width() - forgetPwdDialogEl.outerWidth()) / 2\r\n");
      out.write("                    }).show();\r\n");
      out.write("                    forgetPwdOlEl.show();\r\n");
      out.write("                    $('.mobile', forgetPwdDialogEl).val(\"\");\r\n");
      out.write("                    $('.mobile', forgetPwdDialogEl)[0].focus();\r\n");
      out.write("                    return false;\r\n");
      out.write("                });\r\n");
      out.write("                forgetPwdDialogEl.on('click', '.f-cancel', function () {\r\n");
      out.write("                    forgetPwdDialogEl.hide();\r\n");
      out.write("                    forgetPwdOlEl.hide();\r\n");
      out.write("                }).on('click', '.f-submit', function () {\r\n");
      out.write("                    var mobile = $.trim($('.mobile', forgetPwdDialogEl).val());\r\n");
      out.write("                    if (mobile) {\r\n");
      out.write("                        $.ajax({\r\n");
      out.write("                            type: \"POST\",\r\n");
      out.write("                            url:'login/getPWD.do',\r\n");
      out.write("                            data:{\r\n");
      out.write("                                \"tel\": mobile\r\n");
      out.write("                            },\r\n");
      out.write("                            dataType: \"json\",\r\n");
      out.write("                            success: function(data){\r\n");
      out.write("                                 if(!data.flag) {\r\n");
      out.write("                                    alert(data.message);\r\n");
      out.write("                                 } else {\r\n");
      out.write("                                    alert(data.message);\r\n");
      out.write("                                    forgetPwdDialogEl.hide();\r\n");
      out.write("                                    forgetPwdOlEl.hide();\r\n");
      out.write("                                 }\r\n");
      out.write("                            },\r\n");
      out.write("                            error: function () {\r\n");
      out.write("                                alert(\"服务器连接失败，请与管理员联系\");\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert('请输入手机号');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                winEl.resize(function () {\r\n");
      out.write("                    if (forgetPwdDialogEl.is(':visible')) {\r\n");
      out.write("                        forgetPwdDialogEl.css({\r\n");
      out.write("                            \"top\": (winEl.height() - forgetPwdDialogEl.outerHeight()) / 2,\r\n");
      out.write("                            \"left\": (winEl.width() - forgetPwdDialogEl.outerWidth()) / 2\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                //提交\r\n");
      out.write("                loginFormEl.on('click', '.f-submit', function () {\r\n");
      out.write("                    var tel = $.trim(accountEl.val()),\r\n");
      out.write("                        pwd = $.trim(pwdEl.val()),\r\n");
      out.write("                        softPos = document.getElementById('softPos');\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                         type: \"post\",\r\n");
      out.write("                         contentType : 'application/json',\r\n");
      out.write("                         url:'login/verifyMac.do?tel='+tel,\r\n");
      out.write("                         dataType:\"json\",\r\n");
      out.write("                         success:function(responseData){\r\n");
      out.write("                             var isVerified = false,\r\n");
      out.write("                                 i,\r\n");
      out.write("                                 mac,\r\n");
      out.write("                                 data;\r\n");
      out.write("                             if(!responseData.flag){\r\n");
      out.write("                                 alert(responseData.message);\r\n");
      out.write("                             }else{\r\n");
      out.write("                                 //验证MAC地址是否与本机相同\r\n");
      out.write("                                 data = responseData.data;\r\n");
      out.write("                                 if(!softPos || !softPos.VerifyMAC){\r\n");
      out.write("                                \t //需要给苹果客户端一个入口，如果是mac地址为111111，不需要特殊验证\r\n");
      out.write("                                \t for(i=0; i < data.length; i++){\r\n");
      out.write("\t                                     mac = data[i].mac;\r\n");
      out.write("\t                                     if ('111111'== mac) {\r\n");
      out.write("\t                                        isVerified = true;\r\n");
      out.write("\t                                        break;\r\n");
      out.write("\t                                     }\r\n");
      out.write("\t                                 }\r\n");
      out.write("                                \t if(!isVerified){\r\n");
      out.write("\t                                     alert(\"你的浏览器不支持MAC地址校验, 需要安装一个插件\");\r\n");
      out.write("\t                                     return false;\r\n");
      out.write("                                \t }\r\n");
      out.write("                                }else {\r\n");
      out.write("\t                                 for(i=0; i < data.length; i++){\r\n");
      out.write("\t                                     mac = data[i].mac;\r\n");
      out.write("\t                                     if ('111111'== mac) continue;\r\n");
      out.write("\t                                     if (softPos.VerifyMAC(mac) == 0) {\r\n");
      out.write("\t                                        isVerified = true;\r\n");
      out.write("\t                                        break;\r\n");
      out.write("\t                                     }\r\n");
      out.write("\t                                 }\r\n");
      out.write("                              \t  }\r\n");
      out.write("                                 if(!isVerified){\r\n");
      out.write("                                     alert(\"你只能在自己的电脑上登录\");\r\n");
      out.write("                                     return;\r\n");
      out.write("                                 }else{\r\n");
      out.write("                                      //验证登录用户的用户名和密码合法性\r\n");
      out.write("                                     $.ajax({\r\n");
      out.write("                                        type: \"post\",\r\n");
      out.write("                                        contentType : 'application/json',\r\n");
      out.write("                                        url:'login/loginSubmit.do',\r\n");
      out.write("                                        data: '{\"tel\":\"' + tel + '\", \"password\":\"' + pwd +'\"}',\r\n");
      out.write("                                        dataType:\"json\",\r\n");
      out.write("                                        success:function(responseData){\r\n");
      out.write("                                            var accountStore,\r\n");
      out.write("                                                i;\r\n");
      out.write("                                            if (responseData.flag) {\r\n");
      out.write("                                                if (rememberCkEl.prop('checked')) { //记住密码\r\n");
      out.write("                                                    accountStore = store.get('account') || [];\r\n");
      out.write("                                                    for (i = 0; i < accountStore.length; i++) {\r\n");
      out.write("                                                        if (accountStore[i].account == tel) {\r\n");
      out.write("                                                            //accountStore[i].pwd = pwd;\r\n");
      out.write("                                                            //alreadyExist = true;\r\n");
      out.write("                                                            accountStore.splice(i, 1);  //保证记录最后一次登录最新\r\n");
      out.write("                                                            break;\r\n");
      out.write("                                                        }\r\n");
      out.write("                                                    }\r\n");
      out.write("                                                    accountStore.push({\r\n");
      out.write("                                                        \"account\": tel,\r\n");
      out.write("                                                        \"pwd\": pwd\r\n");
      out.write("                                                    });\r\n");
      out.write("                                                    store.set('account', accountStore);\r\n");
      out.write("                                                }\r\n");
      out.write("                                                location.href = \"./index.jsp\";\r\n");
      out.write("                                            } else {\r\n");
      out.write("                                                alert(responseData[\"message\"]);\r\n");
      out.write("                                            }\r\n");
      out.write("                                        },\r\n");
      out.write("                                        error: function () {\r\n");
      out.write("                                            alert(\"服务器连接失败，请与管理员联系\");\r\n");
      out.write("                                        }\r\n");
      out.write("                                    });\r\n");
      out.write("                                 }\r\n");
      out.write("                             }\r\n");
      out.write("                         },\r\n");
      out.write("                        error: function () {\r\n");
      out.write("                            alert(\"服务器连接失败，请与管理员联系\");\r\n");
      out.write("                        }\r\n");
      out.write("                     });\r\n");
      out.write("                     return false;\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                //测试是否安装flash插件，已安装才可登录\r\n");
      out.write("                if (isFlashPlayerInstalled()) {\r\n");
      out.write("                    noFlashTipEl.hide();\r\n");
      out.write("                    submitEl.removeClass('submit-disabled').prop('disabled', false);\r\n");
      out.write("                } else {\r\n");
      out.write("                    noFlashTipEl.show();\r\n");
      out.write("                    submitEl.addClass('submit-disabled').prop('disabled', true);\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                //debug方式登录\r\n");
      out.write("                var search = location.search,\r\n");
      out.write("                    account,\r\n");
      out.write("                    pwd;\r\n");
      out.write("                if (search) {\r\n");
      out.write("                    search = search.slice(1).split('&');\r\n");
      out.write("                    $.each(search, function (i, param) {\r\n");
      out.write("                        var pArr = param.split('=');\r\n");
      out.write("                        if (pArr[0] === \"account\") {\r\n");
      out.write("                            account = pArr[1];\r\n");
      out.write("                        }\r\n");
      out.write("                        if (pArr[0] === \"pwd\") {\r\n");
      out.write("                            pwd = pArr[1];\r\n");
      out.write("                        }\r\n");
      out.write("                    }); \r\n");
      out.write("                    if (pwd) {\r\n");
      out.write("                        $.ajax({\r\n");
      out.write("                            type: \"post\",\r\n");
      out.write("                            contentType : 'application/json',\r\n");
      out.write("                            url:'login/loginSubmit.do',\r\n");
      out.write("                            data:JSON.stringify({\r\n");
      out.write("                                \"tel\": account,  \r\n");
      out.write("                                \"password\": pwd\r\n");
      out.write("                            }),\r\n");
      out.write("                            dataType:\"json\",\r\n");
      out.write("                            success:function(responseData){\r\n");
      out.write("                                if (responseData.flag) {\r\n");
      out.write("                                    location.href = \"./index.jsp\";\r\n");
      out.write("                                }\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                //私有函数\r\n");
      out.write("                function isFlashPlayerInstalled () {\r\n");
      out.write("                    var isIE = !-[1,],\r\n");
      out.write("                        isInstalled = false;\r\n");
      out.write("                    if(isIE){\r\n");
      out.write("                        try{\r\n");
      out.write("                            var swf1 = new ActiveXObject('ShockwaveFlash.ShockwaveFlash');\r\n");
      out.write("                            isInstalled = true;\r\n");
      out.write("                        } catch(evt){ }\r\n");
      out.write("                    } else {\r\n");
      out.write("                        try{\r\n");
      out.write("                            var swf2 = navigator.plugins['Shockwave Flash'];\r\n");
      out.write("                            if(swf2){\r\n");
      out.write("                                isInstalled = true;\r\n");
      out.write("                            }\r\n");
      out.write("                        } catch(evt){}\r\n");
      out.write("                    }\r\n");
      out.write("                    return isInstalled;\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"page\">\r\n");
      out.write("            <div class=\"page-bd\">\r\n");
      out.write("                <div class=\"page-bd-inner\">\r\n");
      out.write("                    <div class=\"logo page-bd-north\">雅座销售ERP</div>\r\n");
      out.write("                    <div class=\"page-bd-center\">\r\n");
      out.write("                        <form class=\"login-form\" action=\"#\" method=\"post\">\r\n");
      out.write("                            <div class=\"f-title\">用户登录</div>\r\n");
      out.write("                           <!-- <div class=\"f-field fn-clear\">\r\n");
      out.write("                                <label class=\"ff-label fn-left\">组织名：</label>\r\n");
      out.write("                                <div class=\"ff-value fn-left\">\r\n");
      out.write("                                    <input type=\"text\" class=\"organization input-text\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>-->\r\n");
      out.write("                            <div class=\"f-field fn-clear\">\r\n");
      out.write("                                <label class=\"ff-label fn-left\">账&nbsp;&nbsp;号：</label>\r\n");
      out.write("                                <div class=\"ff-value fn-left\">\r\n");
      out.write("                                    <input type=\"text\" class=\"account input-text\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"f-field fn-clear\">\r\n");
      out.write("                                <label class=\"ff-label fn-left\">密&nbsp;&nbsp;码：</label>\r\n");
      out.write("                                <div class=\"ff-value fn-left\">\r\n");
      out.write("                                    <input type=\"password\" class=\"pwd input-text\" />\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"remember-field f-field fn-clear\">\r\n");
      out.write("                                <label class=\"ff-label fn-left\">&nbsp;</label>\r\n");
      out.write("                                <div class=\"ff-value fn-left\">\r\n");
      out.write("                                    <div class=\"ff-value-inner fn-clear\">\r\n");
      out.write("                                        <div class=\"ff-value-l fn-left\">\r\n");
      out.write("                                            <input id=\"is-remember\" type=\"checkbox\" class=\"is-remember\" />&nbsp;&nbsp;<label for=\"is-remember\">记住密码</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"ff-value-r fn-right\">\r\n");
      out.write("                                            <a href=\"#\" class=\"forget-pwd-link\">忘记密码</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"f-field fn-clear\">\r\n");
      out.write("                                <label class=\"ff-label fn-left\">&nbsp;</label>\r\n");
      out.write("                                <div class=\"ff-value fn-left\">\r\n");
      out.write("                                    <button type=\"button\" class=\"f-submit submit-disabled\" disabled=\"disabled\">登&nbsp;录</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"no-flash-tip\">您还没有安装Flash插件，将无法登录ERP系统，点击<a href=\"http://get.adobe.com/cn/flashplayer/\" target=\"_blank\">安装插件</a></div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"page-bd-south fn-clear\">\r\n");
      out.write("                        <div class=\"south-l fn-left\">\r\n");
      out.write("                            <span class=\"icon-yazuo-logo iconfont\"></span>&nbsp;<span class=\"icon-text\">做会员，就找雅座</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"south-r fn-right\">咨询电话：400-1055-888</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 找回密码 -->\r\n");
      out.write("        <div class=\"find-pwd-dialog\">\r\n");
      out.write("            <div class=\"f-field\">\r\n");
      out.write("                <label>手机号：</label><input type=\"text\" class=\"mobile\" name=\"mobile\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"f-action\">\r\n");
      out.write("                <button type=\"button\" class=\"f-submit\">提交</button>&nbsp;&nbsp;<button type=\"button\" class=\"f-cancel\">取消</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"find-pwd-overlay\"></div>\r\n");
      out.write("        <!-- 嵌入插件获得本机MAC地址 -->\r\n");
      out.write("        <embed type=\"application/npsoftpos\" width=0 height=0 id=\"softPos\"/>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
