package com.yazuo.weixin.minimart.vo;

import java.util.Date;

/**
* @ClassName WxMallGoods
* @Description 微信商城商品表
* @author sundongfeng@yazuo.com
* @date 2014-8-6 下午2:36:20
* @version 1.0
*/
public class WxMallGoods implements Comparable<WxMallGoods>{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.type_id
     *
     * @mbggenerated
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.sub_type_id
     *
     * @mbggenerated
     */
    private Integer subTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.goods_status_id
     *
     * @mbggenerated
     */
    private Short goodsStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.picurl
     *
     * @mbggenerated
     */
    private String picurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.intro
     *
     * @mbggenerated
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.rules
     *
     * @mbggenerated
     */
    private String rules;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.payment
     *
     * @mbggenerated
     */
    private Short payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.original_price
     *
     * @mbggenerated
     */
    private Float originalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.original_price_show
     *
     * @mbggenerated
     */
    private Short originalPriceShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.now_price_cash
     *
     * @mbggenerated
     */
    private Float nowPriceCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.now_price_integral
     *
     * @mbggenerated
     */
    private Integer nowPriceIntegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.deals_type_id
     *
     * @mbggenerated
     */
    private Integer dealsTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.buy_limit_is
     *
     * @mbggenerated
     */
    private Short buyLimitIs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.buy_limit_type
     *
     * @mbggenerated
     */
    private Short buyLimitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.buy_limit_num
     *
     * @mbggenerated
     */
    private Integer buyLimitNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.add_time
     *
     * @mbggenerated
     */
    private Date addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.publish_time
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.under_time
     *
     * @mbggenerated
     */
    private Date underTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.brand_id
     *
     * @mbggenerated
     */
    private Integer brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.status
     *
     * @mbggenerated
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.expire_type
     *
     * @mbggenerated
     */
    private Short expireType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.expire_begin
     *
     * @mbggenerated
     */
    private Date expireBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.expire_end
     *
     * @mbggenerated
     */
    private Date expireEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weixin_mall_goods.expire_days
     *
     * @mbggenerated
     */
    private Integer expireDays;
    
    private Integer expireDaysBegin;//
    
    private Short useTimeType;
    //商品种类id
    private Integer categoryId;
    //关联的卡类型id
    private Integer cardTypeId;
    
    //商品库存量
    private Integer remainNum;
    //大类名字
    private String bigName;
    //小类名字
    private String smallName;
    
    private Integer bigOrder;

    private Integer smallOrder;
    private String dealName;
    private String  productType;//电子卡2，实体卡
    private String  batchId;//卡批次
    private String cardPictureUrl; // 卡样图片地址
    
    
    public String getBatchId() {
		return batchId;
	}

	public void setBatchId(String batchId) {
		this.batchId = batchId;
	}

	public String getProductType() {
		return productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	public Integer getExpireDaysBegin() {
		return expireDaysBegin;
	}

	public void setExpireDaysBegin(Integer expireDaysBegin) {
		this.expireDaysBegin = expireDaysBegin;
	}

	public String getDealName() {
		return dealName;
	}

	public void setDealName(String dealName) {
		this.dealName = dealName;
	}

	public Short getUseTimeType() {
		return useTimeType;
	}

	public void setUseTimeType(Short useTimeType) {
		this.useTimeType = useTimeType;
	}

	public Integer getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	public Integer getCardTypeId() {
		return cardTypeId;
	}

	public void setCardTypeId(Integer cardTypeId) {
		this.cardTypeId = cardTypeId;
	}

	public Integer getBigOrder() {
		return bigOrder;
	}

	public void setBigOrder(Integer bigOrder) {
		this.bigOrder = bigOrder;
	}

	public Integer getSmallOrder() {
		return smallOrder;
	}

	public void setSmallOrder(Integer smallOrder) {
		this.smallOrder = smallOrder;
	}

	public String getBigName() {
		return bigName;
	}

	public void setBigName(String bigName) {
		this.bigName = bigName;
	}

	public String getSmallName() {
		return smallName;
	}

	public void setSmallName(String smallName) {
		this.smallName = smallName;
	}

	public Integer getRemainNum() {
		return remainNum;
	}

	public void setRemainNum(Integer remainNum) {
		this.remainNum = remainNum;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.id
     *
     * @return the value of weixin_mall_goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.id
     *
     * @param id the value for weixin_mall_goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.name
     *
     * @return the value of weixin_mall_goods.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.name
     *
     * @param name the value for weixin_mall_goods.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.type_id
     *
     * @return the value of weixin_mall_goods.type_id
     *
     * @mbggenerated
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.type_id
     *
     * @param typeId the value for weixin_mall_goods.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.sub_type_id
     *
     * @return the value of weixin_mall_goods.sub_type_id
     *
     * @mbggenerated
     */
    public Integer getSubTypeId() {
        return subTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.sub_type_id
     *
     * @param subTypeId the value for weixin_mall_goods.sub_type_id
     *
     * @mbggenerated
     */
    public void setSubTypeId(Integer subTypeId) {
        this.subTypeId = subTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.goods_status_id
     *
     * @return the value of weixin_mall_goods.goods_status_id
     *
     * @mbggenerated
     */
    public Short getGoodsStatusId() {
        return goodsStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.goods_status_id
     *
     * @param goodsStatusId the value for weixin_mall_goods.goods_status_id
     *
     * @mbggenerated
     */
    public void setGoodsStatusId(Short goodsStatusId) {
        this.goodsStatusId = goodsStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.picurl
     *
     * @return the value of weixin_mall_goods.picurl
     *
     * @mbggenerated
     */
    public String getPicurl() {
        return picurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.picurl
     *
     * @param picurl the value for weixin_mall_goods.picurl
     *
     * @mbggenerated
     */
    public void setPicurl(String picurl) {
        this.picurl = picurl == null ? null : picurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.intro
     *
     * @return the value of weixin_mall_goods.intro
     *
     * @mbggenerated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.intro
     *
     * @param intro the value for weixin_mall_goods.intro
     *
     * @mbggenerated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.rules
     *
     * @return the value of weixin_mall_goods.rules
     *
     * @mbggenerated
     */
    public String getRules() {
        return rules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.rules
     *
     * @param rules the value for weixin_mall_goods.rules
     *
     * @mbggenerated
     */
    public void setRules(String rules) {
        this.rules = rules == null ? null : rules.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.quantity
     *
     * @return the value of weixin_mall_goods.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.quantity
     *
     * @param quantity the value for weixin_mall_goods.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.payment
     *
     * @return the value of weixin_mall_goods.payment
     *
     * @mbggenerated
     */
    public Short getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.payment
     *
     * @param payment the value for weixin_mall_goods.payment
     *
     * @mbggenerated
     */
    public void setPayment(Short payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.original_price
     *
     * @return the value of weixin_mall_goods.original_price
     *
     * @mbggenerated
     */
    public Float getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.original_price
     *
     * @param originalPrice the value for weixin_mall_goods.original_price
     *
     * @mbggenerated
     */
    public void setOriginalPrice(Float originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.original_price_show
     *
     * @return the value of weixin_mall_goods.original_price_show
     *
     * @mbggenerated
     */
    public Short getOriginalPriceShow() {
        return originalPriceShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.original_price_show
     *
     * @param originalPriceShow the value for weixin_mall_goods.original_price_show
     *
     * @mbggenerated
     */
    public void setOriginalPriceShow(Short originalPriceShow) {
        this.originalPriceShow = originalPriceShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.now_price_cash
     *
     * @return the value of weixin_mall_goods.now_price_cash
     *
     * @mbggenerated
     */
    public Float getNowPriceCash() {
        return nowPriceCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.now_price_cash
     *
     * @param nowPriceCash the value for weixin_mall_goods.now_price_cash
     *
     * @mbggenerated
     */
    public void setNowPriceCash(Float nowPriceCash) {
        this.nowPriceCash = nowPriceCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.now_price_integral
     *
     * @return the value of weixin_mall_goods.now_price_integral
     *
     * @mbggenerated
     */
    public Integer getNowPriceIntegral() {
        return nowPriceIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.now_price_integral
     *
     * @param nowPriceIntegral the value for weixin_mall_goods.now_price_integral
     *
     * @mbggenerated
     */
    public void setNowPriceIntegral(Integer nowPriceIntegral) {
        this.nowPriceIntegral = nowPriceIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.deals_type_id
     *
     * @return the value of weixin_mall_goods.deals_type_id
     *
     * @mbggenerated
     */
    public Integer getDealsTypeId() {
        return dealsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.deals_type_id
     *
     * @param dealsTypeId the value for weixin_mall_goods.deals_type_id
     *
     * @mbggenerated
     */
    public void setDealsTypeId(Integer dealsTypeId) {
        this.dealsTypeId = dealsTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.buy_limit_is
     *
     * @return the value of weixin_mall_goods.buy_limit_is
     *
     * @mbggenerated
     */
    public Short getBuyLimitIs() {
        return buyLimitIs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.buy_limit_is
     *
     * @param buyLimitIs the value for weixin_mall_goods.buy_limit_is
     *
     * @mbggenerated
     */
    public void setBuyLimitIs(Short buyLimitIs) {
        this.buyLimitIs = buyLimitIs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.buy_limit_type
     *
     * @return the value of weixin_mall_goods.buy_limit_type
     *
     * @mbggenerated
     */
    public Short getBuyLimitType() {
        return buyLimitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.buy_limit_type
     *
     * @param buyLimitType the value for weixin_mall_goods.buy_limit_type
     *
     * @mbggenerated
     */
    public void setBuyLimitType(Short buyLimitType) {
        this.buyLimitType = buyLimitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.buy_limit_num
     *
     * @return the value of weixin_mall_goods.buy_limit_num
     *
     * @mbggenerated
     */
    public Integer getBuyLimitNum() {
        return buyLimitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.buy_limit_num
     *
     * @param buyLimitNum the value for weixin_mall_goods.buy_limit_num
     *
     * @mbggenerated
     */
    public void setBuyLimitNum(Integer buyLimitNum) {
        this.buyLimitNum = buyLimitNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.add_time
     *
     * @return the value of weixin_mall_goods.add_time
     *
     * @mbggenerated
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.add_time
     *
     * @param addTime the value for weixin_mall_goods.add_time
     *
     * @mbggenerated
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.update_time
     *
     * @return the value of weixin_mall_goods.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.update_time
     *
     * @param updateTime the value for weixin_mall_goods.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.publish_time
     *
     * @return the value of weixin_mall_goods.publish_time
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.publish_time
     *
     * @param publishTime the value for weixin_mall_goods.publish_time
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.under_time
     *
     * @return the value of weixin_mall_goods.under_time
     *
     * @mbggenerated
     */
    public Date getUnderTime() {
        return underTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.under_time
     *
     * @param underTime the value for weixin_mall_goods.under_time
     *
     * @mbggenerated
     */
    public void setUnderTime(Date underTime) {
        this.underTime = underTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.operator
     *
     * @return the value of weixin_mall_goods.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.operator
     *
     * @param operator the value for weixin_mall_goods.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.brand_id
     *
     * @return the value of weixin_mall_goods.brand_id
     *
     * @mbggenerated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.brand_id
     *
     * @param brandId the value for weixin_mall_goods.brand_id
     *
     * @mbggenerated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.status
     *
     * @return the value of weixin_mall_goods.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.status
     *
     * @param status the value for weixin_mall_goods.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.expire_type
     *
     * @return the value of weixin_mall_goods.expire_type
     *
     * @mbggenerated
     */
    public Short getExpireType() {
        return expireType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.expire_type
     *
     * @param expireType the value for weixin_mall_goods.expire_type
     *
     * @mbggenerated
     */
    public void setExpireType(Short expireType) {
        this.expireType = expireType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.expire_begin
     *
     * @return the value of weixin_mall_goods.expire_begin
     *
     * @mbggenerated
     */
    public Date getExpireBegin() {
        return expireBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.expire_begin
     *
     * @param expireBegin the value for weixin_mall_goods.expire_begin
     *
     * @mbggenerated
     */
    public void setExpireBegin(Date expireBegin) {
        this.expireBegin = expireBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.expire_end
     *
     * @return the value of weixin_mall_goods.expire_end
     *
     * @mbggenerated
     */
    public Date getExpireEnd() {
        return expireEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.expire_end
     *
     * @param expireEnd the value for weixin_mall_goods.expire_end
     *
     * @mbggenerated
     */
    public void setExpireEnd(Date expireEnd) {
        this.expireEnd = expireEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weixin_mall_goods.expire_days
     *
     * @return the value of weixin_mall_goods.expire_days
     *
     * @mbggenerated
     */
    public Integer getExpireDays() {
        return expireDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weixin_mall_goods.expire_days
     *
     * @param expireDays the value for weixin_mall_goods.expire_days
     *
     * @mbggenerated
     */
    public void setExpireDays(Integer expireDays) {
        this.expireDays = expireDays;
    }
    
	public String getCardPictureUrl() {
		return cardPictureUrl;
	}

	public void setCardPictureUrl(String cardPictureUrl) {
		this.cardPictureUrl = cardPictureUrl;
	}

	public int compareTo(WxMallGoods o) {
		short a = this.getGoodsStatusId();
		short b = o.getGoodsStatusId();
		if(a<b){
			return -1;
		}else{
			return 1;
		}
	}
}